dist: trusty
language: ruby


sudo: required
services:
  - docker


script: |
  .travis.d/build.sh &&
  cd .travis.d &&
  bundle install --gemfile=Gemfile --path vendor/bundle &&
  BUNDLE_GEMFILE=Gemfile bundle exec ruby pr_autodeploy.rb

env:
  global:
    - HACKGPROJECT_REV="12e4e42b0c2326e36f97d5624221e898fbe45872"

    - DOCKER_ID_USER="hackgt"

