FROM kterada0509/docker-revel:1.9-stretch

# Setup nodejs for webpack
RUN curl -sL https://deb.nodesource.com/setup_6.x | bash -

# Install node
RUN apt-get update && apt-get install -y \
    nodejs

WORKDIR /src

CMD bash build.sh
