[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6"

[[constraint]]
  name = "github.com/gorilla/handlers"
  version = "1.3"

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "1.3"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0"

[[constraint]]
  name = "github.com/jmoiron/sqlx"
  branch = "master"

[[constraint]]
  name = "github.com/lib/pq"
  branch = "master"

[[constraint]]
  name = "github.com/mattes/migrate"
  version = "3.0.0"
