[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6"

[[constraint]]
  name = "github.com/gorilla/handlers"
  version = "1.3"

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "1.3"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0"

[prune]
  go-tests = true
  unused-packages = true
