// Boilerplate examples
export const CHANGING_MESSAGE = 'CHANGING_MESSAGE';
export const CHANGED_MESSAGE = 'CHANGED_MESSAGE';

// participants (profile list)
export const LOAD_PARTICIPANTS = 'LOAD_PARTICIPANTS';
export const LOAD_PARTICIPANTS_SUCCESS = 'LOAD_PARTICIPANTS_SUCCESS';
export const LOAD_PARTICIPANTS_FAILURE = 'LOAD_PARTICIPANTS_FAILURE';
export const SELECT_PARTICIPANT = 'SELECT_PARTICIPANT';
export const UNSELECT_PARTICIPANT = 'UNSELECT_PARTICIPANT';
export const TAG_PARTICIPANT = 'TAG_PARTICIPANT';
export const SHOW_PARTICIPANT = 'SHOW_PARTICIPANT';
export const HIDE_PARTICIPANT = 'HIDE_PARTICIPANT';
export const SEARCH_PARTICIPANTS = 'SEARCH_PARTICIPANTS';

// search
export const SEARCH_BY_KEYWORD = 'SEARCH_BY_KEYWORD';
export const SEARCH_BY_KEYWORD_SUCCESS = 'SEARCH_BY_KEYWORD_SUCCESS';
export const SEARCH_BY_KEYWORD_FAILURE = 'SEARCH_BY_KEYWORD_FAILURE';

// ui
export const LOADER_ON = 'LOADER_ON';
export const LOADER_OFF = 'LOADER_OFF';
export const MODAL_ON = 'MODAL_ON';
export const MODAL_OFF = 'MODAL_OFF';
export const UI_UPDATE_SYNC_STATUS = 'UI_UPDATE_SYNC_STATUS';
export const TABLE_LOADER_ON = 'TABLE_LOADER_ON';
export const TABLE_LOADER_OFF = 'TABLE_LOADER_OFF';
export const UI_UPDATE_PDF_URL = 'UI_UPDATE_PDF_URL';
export const UI_PDF_MODAL_ON = 'UI_PDF_MODAL_ON';
export const UI_PDF_MODAL_OFF = 'UI_PDF_MODAL_OFF';

// auth
export const LOG_IN = 'LOG_IN';
export const LOG_OUT = 'LOG_OUT';

